In [6]:
# !conda install numpy
# !conda list numpy
# !conda list
# !conda --version

In [1]:
import numpy as np

In [9]:
np.__version__

'1.19.1'

## Array

In [40]:
arr1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(arr1, arr1.dtype)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] int64


In [15]:
print(arr1[0])
print(arr1[3])
print(arr1[-1])

[1 2 3]
[10 11 12]
[10 11 12]


In [16]:
list1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]
print(list1)

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]


In [21]:
print(list1[0][0])
print(list1[0,0])

1


TypeError: list indices must be integers or slices, not tuple

In [29]:
list1[0][0], list1[1][0], list1[2][0], list1[3][0]

(1, 4, 7, 10)

In [26]:
print(arr1[0, 0])
print(arr1[0])
print(arr1[:, 0])    # column
print(arr1[:])

1
[1 2 3]
[ 1  4  7 10]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [38]:
arr1.dtype, type(arr1)

(dtype('int64'), numpy.ndarray)

In [32]:
arr2 = np.array([[.1, .2], [.3, .4]])
print(arr2)
print(arr2.dtype)

[[0.1 0.2]
 [0.3 0.4]]
float64


In [46]:
arr3 = np.array([
    [
        [1, 2, 3],
        [11, 22, 33]
    ],
    [
        [4, 5, 6],
        [44, 55, 66]
    ]
])
print(arr3)

[[[ 1  2  3]
  [11 22 33]]

 [[ 4  5  6]
  [44 55 66]]]


In [47]:
np.array([[1, 2, 3], [1, 2]])

/Users/syahrulhamdani/.pyenv/versions/3.7.7/envs/PYTN/lib/python3.7/site-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.


array([list([1, 2, 3]), list([1, 2])], dtype=object)

In [45]:
# shape of array
print("shape of arr1:", arr1.shape)
print("shape of arr2:", arr2.shape)
print("shape of arr2:", arr3.shape)

print("dimension of arr1:", arr1.ndim)
print("dimension of arr2:", arr2.ndim)
print("dimension of arr2:", arr3.ndim)

shape of arr1: (4, 3)
shape of arr2: (2, 2)
shape of arr2: (2, 2, 3)
dimension of arr1: 2
dimension of arr2: 2
dimension of arr2: 3


In [54]:
arr_zeros_1 = np.zeros(10)
shape_2 = [10, 5]
arr_zeros_2 = np.zeros(shape_2)
arr_zeros_3 = np.zeros([5, 10, 10])

print(arr_zeros_1, arr_zeros_1.shape)
print("--")
print(arr_zeros_2, arr_zeros_2.shape)
print("--")
print(arr_zeros_3, arr_zeros_3.shape)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] (10,)
--
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] (10, 5)
--
[[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 

In [53]:
arr_ones_1 = np.ones(10)
arr_ones_2 = np.ones((10, 5))
arr_ones_3 = np.ones([5, 10, 10])

print(arr_ones_1, arr_ones_1.shape)
print("--")
print(arr_ones_2, arr_ones_2.shape)
print("--")
print(arr_ones_3, arr_ones_3.shape)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] (10,)
--
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] (10, 5)
--
[[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 

In [72]:
arr_empty = np.empty((100, 100))
print(arr_empty, arr_empty.shape)

[[0.00000000e+000 0.00000000e+000 0.00000000e+000 ... 7.74860419e-304
  7.74860419e-304 7.74860419e-304]
 [7.74860419e-304 7.74860419e-304 7.74860419e-304 ... 7.74860419e-304
  7.74860419e-304 7.74860419e-304]
 [7.74860419e-304 7.74860419e-304 7.74860419e-304 ... 7.74860419e-304
  7.74860419e-304 7.74860419e-304]
 ...
 [2.21823531e-314 2.21824279e-314 2.21824284e-314 ... 2.21823721e-314
  2.21824534e-314 2.21824412e-314]
 [2.21824417e-314 2.21821193e-314 2.21824421e-314 ... 2.21824943e-314
  2.21824774e-314 2.21824779e-314]
 [2.21824947e-314 2.21824783e-314 2.21824951e-314 ... 2.21825324e-314
  2.21825329e-314 2.21825334e-314]] (100, 100)


In [76]:
print(np.arange(0, 100, 2))
print(np.arange(10))

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]
[0 1 2 3 4 5 6 7 8 9]


In [80]:
arr_one = np.array([1, 2, 3, 4, 5])
arr_one

array([1, 2, 3, 4, 5])

In [98]:
np.append(arr_one, [10, 10])

array([ 1,  2,  3,  4,  5, 10, 10])

In [101]:
# arr4 = 
np.append(arr1, [[13, 14, 15], [16, 17, 18]], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [93]:
np.array([[13], [14], [15], [10], [11]]).shape, arr1.shape

((5, 1), (4, 3))

In [95]:
np.append(arr1, [[13], [14], [15], [10]], axis=1)

array([[ 1,  2,  3, 13],
       [ 4,  5,  6, 14],
       [ 7,  8,  9, 15],
       [10, 11, 12, 10]])

In [103]:
arr_ones_3.shape

(5, 10, 10)

In [107]:
# np.append(arr_ones_3, np.zeros((1, 10, 10)), axis=0)
np.append(arr_ones_3, np.zeros((1, 10, 10)), axis=0).shape

(6, 10, 10)

In [111]:
[1, 2, 3] + [1]

[1, 2, 3, 1]

In [113]:
arr1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [119]:
arr1.shape

(4, 3)

In [120]:
np.delete(arr1, 0, axis=1)

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [123]:
arr_unsorted = np.array([3, 6, 1, 56, 1, 0])
print(arr_unsorted)
np.sort(arr_unsorted)

[ 3  6  1 56  1  0]


array([ 0,  1,  1,  3,  6, 56])

In [130]:
arr1[0] = [5, 11, 10]
arr1

array([[ 5, 11, 10],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [132]:
print(np.sort(arr1))
print(np.sort(arr1, axis=0))

[[ 5 10 11]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 4  5  6]
 [ 5  8  9]
 [ 7 11 10]
 [10 11 12]]


In [136]:
arr_one

array([1, 2, 3, 4, 5])

In [135]:
arr_one.shape, arr1.shape

((5,), (4, 3))

In [138]:
vector_col = np.array([[1], [2], [3], [4], [5]])
print(vector_col, vector_col.shape)

[[1]
 [2]
 [3]
 [4]
 [5]] (5, 1)


In [145]:
print(np.reshape(arr1, (3, 4)))
print(np.reshape(arr1, (2, 6)))
print(np.reshape(arr1, (2, 2, 3)))
print(np.reshape(arr1, (1, 4, 3)))
print(np.reshape(arr1, (4, 1, 3)))

[[ 5 11 10  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 5 11 10  4  5  6]
 [ 7  8  9 10 11 12]]
[[[ 5 11 10]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[ 5 11 10]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]
[[[ 5 11 10]]

 [[ 4  5  6]]

 [[ 7  8  9]]

 [[10 11 12]]]


In [141]:
arr1

array([[ 5, 11, 10],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [154]:
arr1[..., np.newaxis].shape, arr1[:, :, np.newaxis].shape

((4, 3, 1), (4, 3, 1))

In [156]:
arr1.flatten()

array([ 5, 11, 10,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [155]:
arr1[arr1 > 5]

array([11, 10,  6,  7,  8,  9, 10, 11, 12])

In [158]:
arr1[(arr1 % 2 == 0) & (arr1 > 5)]

array([10,  6,  8, 10, 12])

In [161]:
arr1[(arr1 % 2 == 0) | (arr1 % 3 == 0)]

array([10,  4,  6,  8,  9, 10, 12])

In [164]:
np.expand_dims(arr1, axis=1)

array([[[ 5, 11, 10]],

       [[ 4,  5,  6]],

       [[ 7,  8,  9]],

       [[10, 11, 12]]])

In [162]:
arr1.reshape(2, 2, 3)

array([[[ 5, 11, 10],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [168]:
arr11 = arr1 * 10
print(arr1)
print(arr11)

[[ 5 11 10]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 50 110 100]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]


In [172]:
print(np.concatenate((arr1, arr11)))
print(np.concatenate((arr1, arr11), axis=1))

[[  5  11  10]
 [  4   5   6]
 [  7   8   9]
 [ 10  11  12]
 [ 50 110 100]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]
[[  5  11  10  50 110 100]
 [  4   5   6  40  50  60]
 [  7   8   9  70  80  90]
 [ 10  11  12 100 110 120]]


In [181]:
# print(arr1.sum(), np.sum(arr1), sum(arr1))
print(arr1)
print(arr1.sum(axis=0))
print(arr1.sum(axis=1))

[[ 5 11 10]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[26 35 37]
[26 15 24 33]


In [182]:
print(arr1.std(), arr1.mean(), arr1.max(), arr1.min())

2.6087459737497545 8.166666666666666 12 4


In [185]:
arr1.shape, arr11.shape

((4, 3), (4, 3))

In [192]:
print(arr11)
print(arr1)

[[ 50 110 100]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]
[[ 5 11 10]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [193]:
print(arr1 + arr11)   # penjumlahan
print(arr1.dot(arr11.T))   # matrix multiplication -> or np.dot(arr1, arr11.T)
print(np.multiply(arr1, arr11))
arr1 * arr11

[[ 55 121 110]
 [ 44  55  66]
 [ 77  88  99]
 [110 121 132]]
[[2460 1350 2130 2910]
 [1350  770 1220 1670]
 [2130 1220 1940 2660]
 [2910 1670 2660 3650]]
[[ 250 1210 1000]
 [ 160  250  360]
 [ 490  640  810]
 [1000 1210 1440]]


array([[ 250, 1210, 1000],
       [ 160,  250,  360],
       [ 490,  640,  810],
       [1000, 1210, 1440]])

In [196]:
arr1.dot(np.array([3, 3, 3]))

array([78, 45, 72, 99])

In [197]:
np.matmul(arr1, np.array([3, 3, 3]))

array([78, 45, 72, 99])

In [198]:
a = np.ones([9, 5, 7, 4])
c = np.ones([9, 5, 4, 3])
np.dot(a, c)

array([[[[[[4., 4., 4.],
           [4., 4., 4.],
           [4., 4., 4.],
           [4., 4., 4.],
           [4., 4., 4.]],

          [[4., 4., 4.],
           [4., 4., 4.],
           [4., 4., 4.],
           [4., 4., 4.],
           [4., 4., 4.]],

          [[4., 4., 4.],
           [4., 4., 4.],
           [4., 4., 4.],
           [4., 4., 4.],
           [4., 4., 4.]],

          ...,

          [[4., 4., 4.],
           [4., 4., 4.],
           [4., 4., 4.],
           [4., 4., 4.],
           [4., 4., 4.]],

          [[4., 4., 4.],
           [4., 4., 4.],
           [4., 4., 4.],
           [4., 4., 4.],
           [4., 4., 4.]],

          [[4., 4., 4.],
           [4., 4., 4.],
           [4., 4., 4.],
           [4., 4., 4.],
           [4., 4., 4.]]],


         [[[4., 4., 4.],
           [4., 4., 4.],
           [4., 4., 4.],
           [4., 4., 4.],
           [4., 4., 4.]],

          [[4., 4., 4.],
           [4., 4., 4.],
           [4., 4., 4.],
           [4., 4.

In [13]:
arr = np.arange(0, 1, 5e-2)[:, None]
print(arr)
print(arr.shape)
arr = arr.reshape((10, 2))
print(arr.shape)
arr_2 = arr.dot(2)
print(arr_2)
mm = np.matmul(arr, arr_2.T)
print(mm)
print(mm.shape)

[[0.  ]
 [0.05]
 [0.1 ]
 [0.15]
 [0.2 ]
 [0.25]
 [0.3 ]
 [0.35]
 [0.4 ]
 [0.45]
 [0.5 ]
 [0.55]
 [0.6 ]
 [0.65]
 [0.7 ]
 [0.75]
 [0.8 ]
 [0.85]
 [0.9 ]
 [0.95]]
(20, 1)
(10, 2)
[[0.  0.1]
 [0.2 0.3]
 [0.4 0.5]
 [0.6 0.7]
 [0.8 0.9]
 [1.  1.1]
 [1.2 1.3]
 [1.4 1.5]
 [1.6 1.7]
 [1.8 1.9]]
[[0.005 0.015 0.025 0.035 0.045 0.055 0.065 0.075 0.085 0.095]
 [0.015 0.065 0.115 0.165 0.215 0.265 0.315 0.365 0.415 0.465]
 [0.025 0.115 0.205 0.295 0.385 0.475 0.565 0.655 0.745 0.835]
 [0.035 0.165 0.295 0.425 0.555 0.685 0.815 0.945 1.075 1.205]
 [0.045 0.215 0.385 0.555 0.725 0.895 1.065 1.235 1.405 1.575]
 [0.055 0.265 0.475 0.685 0.895 1.105 1.315 1.525 1.735 1.945]
 [0.065 0.315 0.565 0.815 1.065 1.315 1.565 1.815 2.065 2.315]
 [0.075 0.365 0.655 0.945 1.235 1.525 1.815 2.105 2.395 2.685]
 [0.085 0.415 0.745 1.075 1.405 1.735 2.065 2.395 2.725 3.055]
 [0.095 0.465 0.835 1.205 1.575 1.945 2.315 2.685 3.055 3.425]]
(10, 10)


In [24]:
mm_mean = mm.mean(axis=0)
print(mm_mean)
mm_median = np.median(mm, axis=0)
print(mm_median)
mm_std = mm.std(axis=0)
print(mm_std)
mm_var = mm.var(axis=0)
print(mm_var)

[0.05 0.24 0.43 0.62 0.81 1.   1.19 1.38 1.57 1.76]
[0.05 0.24 0.43 0.62 0.81 1.   1.19 1.38 1.57 1.76]
[0.02872281 0.14361407 0.25850532 0.37339657 0.48828782 0.60317908
 0.71807033 0.83296158 0.94785284 1.06274409]
[8.250000e-04 2.062500e-02 6.682500e-02 1.394250e-01 2.384250e-01
 3.638250e-01 5.156250e-01 6.938250e-01 8.984250e-01 1.129425e+00]


In [85]:
# np.random.seed(10)
rand_int = np.random.randint(5, 10, size=(3, 2))
print(rand_int)
rand_uniform = np.random.uniform(size=(3, 2))
print(rand_uniform)
rand_normal = np.random.normal(1., 5., size=(3, 2))
print(rand_normal)

[[6 9]
 [5 6]
 [8 9]]
[[0.49850701 0.22479665]
 [0.19806286 0.76053071]
 [0.16911084 0.08833981]]
[[2.32755793 1.54274263]
 [1.02145715 0.12699895]
 [3.16513095 7.01518687]]
